# Info
baseURL = 'https://masonsq.aao.fyi/'
languageCode = 'en'
title = 'MasonSQ'
copyright = 'aao.fyi'

# Theme
# Replace 'gitlab.com' with 'github.com' if error loading
theme = 'gitlab.com/aao-fyi/shock'

# Features
disableHugoGeneratorInject = false
disableKinds = []
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.110.0'
