# Theme
# Replace 'gitlab.com' with 'github.com' if error loading
theme = 'gitlab.com/aao-fyi/shock'

# Modules
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.110.0' # If changed, update theme.toml
