name = 'masonsq'
license = 'MIT'
licenselink = 'https://gitlab.com/aao-fyi/masonsq/-/blob/main/LICENSE'
description = 'Masonry template for Hugo.'
homepage = 'https://gitlab.com/aao-fyi/masonsq'
tags = ['bootstrap', 'shock', 'grid', 'portfolio']
features = []
min_version = '0.110.0' # If changed, update hugo.toml

[author]
  name = 'aao.fyi'
  homepage = 'https://aao.fyi/'

[original]
  name = 'Michael Crawford'
  homepage = 'https://crawford.io/'
